//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeRank.Database.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public Exam()
        {
            this.ExamResults = new HashSet<ExamResult>();
        }
    
        public int ExamID { get; set; }
        public int CandidateID { get; set; }
        public int PaperSetID { get; set; }
        public System.DateTime ExamDate { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual PaperSet PaperSet { get; set; }
        public virtual ICollection<ExamResult> ExamResults { get; set; }
    }
}
