//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeRank.Database.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperSet
    {
        public PaperSet()
        {
            this.PaperSetQuestions = new HashSet<PaperSetQuestion>();
        }
    
        public int PaperSetID { get; set; }
        public string Description { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual ICollection<PaperSetQuestion> PaperSetQuestions { get; set; }
    }
}
