//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeRank.Database.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperSetQuestion
    {
        public PaperSetQuestion()
        {
            this.ExamResults = new HashSet<ExamResult>();
        }
    
        public int PaperSetQuestionID { get; set; }
        public int PaperSetID { get; set; }
        public int QuestionID { get; set; }
        public short MaximumMarks { get; set; }
    
        public virtual ICollection<ExamResult> ExamResults { get; set; }
        public virtual PaperSet PaperSet { get; set; }
        public virtual Question Question { get; set; }
    }
}
