//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeRank.Database.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.PaperSetQuestions = new HashSet<PaperSetQuestion>();
        }
    
        public int QuestionID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public short ComplexityLevel { get; set; }
        public string TestAssemblyName { get; set; }
    
        public virtual ICollection<PaperSetQuestion> PaperSetQuestions { get; set; }
    }
}
